#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "master" ]; then
  echo "ERROR: Direkter Commit auf 'master' ist nicht erlaubt."
  echo "       Bitte einen Feature-Branch erstellen und per PR mergen."
  exit 1
fi
